// @ts-nocheck -- deterministic browser fixture, checked at the protocol boundary.
import type {AppState,CueDraft,HostMessage,WebMessage} from "../protocol";
import {buildCueDraft,emptyCueForm} from "../cue-draft";
const base=(id:string,name:string,time:string,address:string)=>({id,name,memo:"",triggerTime:time,effectiveTriggerTime:time,frameRate:"30" as const,oscAddress:address,additionalOscAddresses:[],arguments:[],targetHostIds:["qlab"],enabled:true,sendTriggerTimeAsSeconds:false,sendTimecode:null,triggerOffset:null,autoMuteOnFire:false,autoUnmuteAfter:null,runtime:{lastTriggeredAtUtc:null,flashToken:0,muteCountdownText:""}});
export function fakeState():AppState {const clock={raw:"01:24:16:00",display:"01:24:16:08",totalFrames:151688,frameRate:"30" as const,dropFrame:false,receivedAtMonotonicMs:0,nextCueId:"cue-2",framesUntilNextCue:112};return {sessionId:"fake-session",project:{displayName:"show_A.tcb3",filePath:null,dirty:false,canUndo:false,canRedo:false,recentFiles:[]},mode:"ltc",transport:{status:"receiving",statusText:"受信中",detailText:"CH 1 · 48 kHz",signalErrorRatePercent:0,locked:true,triggerMuted:false,autoMuteEnabled:false,autoMutedCueId:null,autoUnmuteAtUtc:null,lastLtcReceivedAtUtc:null},receive:{selectedDeviceId:"in",devices:[{id:"in",name:"UR44 — Input 1 / 2",loopback:false}],offset:"+00:00:00:08",triggerWindowFrames:3,freerunDurationSeconds:1},generator:{running:false,startTime:"01:00:00:00",frameRate:"30",selectedOutputDeviceId:"out",outputDevices:[{id:"out",name:"UR44 — Output 1 / 2",loopback:false}],volume:.4,ltcOutputActive:false,settingsPendingReset:false},currentClock:clock,nextCue:{id:"cue-2",name:"タイトル OUT",triggerTime:"01:24:20:00",effectiveTriggerTime:"01:24:20:00",framesUntil:112},cues:[base("cue-1","本編 IN","01:23:40:00","/qlab/go"),base("cue-2","タイトル OUT","01:24:20:00","/video/title/out")],hosts:[{id:"qlab",name:"QLab — Main",ipAddress:"192.168.1.20",port:53000,enabled:true,reachability:"reachable"},{id:"reso",name:"Resolume — Stage",ipAddress:"192.168.1.31",port:7000,enabled:true,reachability:"reachable"}],cueSync:{oscAddress:"/cuesync",targetHostIds:["qlab","reso"]},triggerPanel:{rows:4,columns:4,buttons:[{id:"go",row:0,column:0,label:"GO",oscAddress:"/go",arguments:[],targetHostIds:["qlab"]}]},logs:[{id:"log-1",timestampUtc:new Date(Date.now()-1000).toISOString(),message:"fake-host を開始しました",success:true}],uiCapabilities:{supportsNativeOpenDialog:false,supportsNativeSaveDialog:false,platform:"macos"}}}
export interface FakeHostHandle{dispose:()=>void}
export function installFakeHost():FakeHostHandle {let state=fakeState(),rev=1,seq=0,serial=10,active=true,timer:number|null=null;const emit=(m:HostMessage)=>queueMicrotask(()=>active&&window.tcb.receive(JSON.stringify(m)));const patch=(changes:Record<string,unknown>)=>{const{logsAppend,logsReset,...replace}=changes;state={...state,...replace};if(logsReset)state.logs=logsReset;if(logsAppend)state.logs=[...state.logs,...logsAppend];emit({protocolVersion:1,type:"patch",baseRevision:rev,revision:++rev,changes})};const invoke=(json:string)=>{const m=JSON.parse(json) as WebMessage;if(m.type==="ready"||m.type==="resync"){emit({protocolVersion:1,type:"snapshot",revision:rev,state});if(timer===null)timer=window.setInterval(()=>emit({protocolVersion:1,type:"clock",seq:++seq,clock:{...state.currentClock,receivedAtMonotonicMs:performance.now()}}),100);return}if(m.type!=="command")return;const a=m.args as Record<string,any>;const ok=(data?:unknown)=>emit({protocolVersion:1,type:"result",requestId:m.requestId,ok:true,data,revision:rev});const fail=(fieldErrors:Record<string,string>)=>emit({protocolVersion:1,type:"result",requestId:m.requestId,ok:false,error:{code:"validation",message:"入力を確認してください",retryable:false,fieldErrors}});const log=(message:string,success=true)=>patch({logsAppend:[{id:`log-${++serial}`,timestampUtc:new Date().toISOString(),message,success}]});
 if(m.command==="mode.set"){const mode=a.mode,ltcStarted=mode==="ltc"&&Boolean(state.receive.selectedDeviceId);patch({mode,transport:{...state.transport,status:ltcStarted?"receiving":"stopped",statusText:ltcStarted?"受信中":mode==="ltc"?"停止中":"生成待機",locked:ltcStarted}});ok({ltcStarted});return}
 if(m.command==="ltc.stop"){patch({transport:{...state.transport,status:"stopped",statusText:"停止",locked:false}});ok();return}
 if(m.command==="receive.selectDevice"&&!(a.deviceId??"")){patch({receive:{...state.receive,selectedDeviceId:null},transport:{...state.transport,status:"stopped",statusText:"停止中",locked:false}});ok();return}
 if(m.command==="receive.selectDevice"){patch({receive:{...state.receive,selectedDeviceId:a.deviceId},transport:{...state.transport,status:"receiving",statusText:"受信中",locked:true}});ok();return}
 if(m.command==="ltc.start"||m.command==="ltc.reconnect"){patch({receive:{...state.receive,selectedDeviceId:a.deviceId??state.receive.selectedDeviceId},transport:{...state.transport,status:"receiving",statusText:"受信中",locked:true}});ok();return}
 if(m.command==="receive.setFreerunDuration"){patch({receive:{...state.receive,freerunDurationSeconds:Number(a.seconds)}});ok();return}
 if(m.command==="audio.refreshDevices"){patch(a.direction==="capture"?{receive:{...state.receive}}:{generator:{...state.generator}});ok();return}
 if(m.command==="generator.configure"){patch({generator:{...state.generator,startTime:a.startTime,frameRate:a.frameRate,selectedOutputDeviceId:a.outputDeviceId||null,volume:a.volume,settingsPendingReset:state.generator.running}});ok();return}
 if(m.command==="generator.start"||m.command==="generator.stop"){const running=m.command.endsWith("start");patch({generator:{...state.generator,running,ltcOutputActive:running&&Boolean(state.generator.selectedOutputDeviceId),settingsPendingReset:false},transport:{...state.transport,status:running?"receiving":"stopped",statusText:running?"生成中":"停止"}});ok();return}
 if(m.command==="generator.reset"){patch({generator:{...state.generator,running:false,ltcOutputActive:false,settingsPendingReset:false},currentClock:{...state.currentClock,raw:state.generator.startTime,display:state.generator.startTime}});ok();return}
 if(m.command==="host.add"||m.command==="host.update"){const h=a.host,e={...(!h.name?{"host.name":"必須"}:{}),...(!h.ipAddress?{"host.ipAddress":"必須"}:{}),...(!(h.port>=1&&h.port<=65535)?{"host.port":"1〜65535"}:{})};if(Object.keys(e).length){fail(e);return}const id=m.command==="host.add"?`host-${++serial}`:String(a.id),host={id,name:h.name,ipAddress:h.ipAddress,port:h.port,enabled:h.enabled??true,reachability:"unknown"};patch({hosts:m.command==="host.add"?[...state.hosts,host]:state.hosts.map(x=>x.id===id?host:x)});ok({id});return}
 if(m.command==="host.remove"){patch({hosts:state.hosts.filter(x=>x.id!==a.id)});ok();return}if(m.command==="host.setEnabled"){patch({hosts:state.hosts.map(x=>x.id===a.id?{...x,enabled:Boolean(a.enabled)}:x)});ok();return}if(m.command==="host.ping"){patch({hosts:state.hosts.map(x=>x.id===a.id?{...x,reachability:"reachable"}:x)});ok({reachable:true,latencyMs:2});return}
 
 if(m.command==="triggerPanel.configureGrid"){patch({triggerPanel:{...state.triggerPanel,rows:Number(a.rows),columns:Number(a.columns),buttons:state.triggerPanel.buttons.filter(x=>x.row<Number(a.rows)&&x.column<Number(a.columns))}});ok();return}if(m.command==="triggerPanel.upsertButton"){const id=a.button.id??`trigger-${++serial}`,button={...a.button,id};patch({triggerPanel:{...state.triggerPanel,buttons:[...state.triggerPanel.buttons.filter(x=>x.id!==id),button]}});ok({id});return}if(m.command==="triggerPanel.removeButton"){patch({triggerPanel:{...state.triggerPanel,buttons:state.triggerPanel.buttons.filter(x=>x.id!==a.id)}});ok();return}if(m.command==="triggerPanel.fire"){log(`ポン出し: ${state.triggerPanel.buttons.find(x=>x.id===a.id)?.label??a.id}`);ok({sent:true,sentCount:1,skippedHostIds:[],reason:"None"});return}
 if(m.command==="logs.clear"){patch({logsReset:[]});ok();return}if(m.command==="cueSync.configure"){patch({cueSync:{...state.cueSync,...a}});ok();return}if(m.command==="cueSync.send"){log("Cue-Sync を送信しました");ok({sent:true,sentCount:2,skippedHostIds:[]});return}
 if(m.command==="cue.add"||m.command==="cue.update"){const d=a.cue as CueDraft,f={...emptyCueForm(d.frameRate??"30"),...d,additionalOscAddresses:(d.additionalOscAddresses??[]).join("\n"),argumentsText:(d.arguments??[]).map(x=>`${x.type}:${x.value}`).join("\n"),sendTimecode:d.sendTimecode??"",triggerOffset:d.triggerOffset??"",autoUnmuteAfter:d.autoUnmuteAfter??""},v=buildCueDraft(f);if(!v.draft){fail(Object.fromEntries(Object.entries(v.errors).map(([k,x])=>[`cue.${k}`,x])));return}const id=m.command==="cue.add"?`cue-${++serial}`:String(a.id),q={...base(id,v.draft.name,v.draft.triggerTime,v.draft.oscAddress),...v.draft,id,effectiveTriggerTime:v.draft.triggerTime};patch({cues:m.command==="cue.add"?[...state.cues,q]:state.cues.map(x=>x.id===id?q:x),project:{...state.project,dirty:true,canUndo:true}});ok({id});return}
 if(m.command==="cue.remove"){patch({cues:state.cues.filter(x=>!a.ids.includes(x.id))});ok();return}if(m.command==="cue.duplicate"){const q=state.cues.find(x=>x.id===a.id),ids:string[]=[];if(q){const copies=Array.from({length:Number(a.count??1)},(_,i)=>{const id=`cue-${++serial}`;ids.push(id);return{...q,id,name:`${q.name} (コピー${i?` ${i+1}`:""})`}});patch({cues:[...state.cues,...copies]})}ok({ids});return}if(m.command==="cue.batchUpdate"){patch({cues:state.cues.map(q=>a.ids.includes(q.id)?{...q,...a.changes}:q)});ok({updated:a.ids.length,offsetSkipped:0});return}
 if(m.command.startsWith("project.")){patch({...(m.command==="project.new"?{cues:[]}:{}),project:{...state.project,displayName:m.command==="project.new"?"名称未設定.tcb3":state.project.displayName,dirty:false,canUndo:false,canRedo:false}});ok({cancelled:false});return}if(m.command==="app.undo"||m.command==="app.redo"){patch({project:{...state.project,canUndo:m.command==="app.redo",canRedo:m.command==="app.undo"}});ok();return}if(m.command==="mute.set")patch({transport:{...state.transport,triggerMuted:Boolean(a.muted)}});if(m.command==="cue.setEnabled")patch({cues:state.cues.map(q=>q.id===a.id?{...q,enabled:Boolean(a.enabled)}:q)});ok()};window.invokeCSharpAction=invoke;return {dispose:()=>{active=false;if(timer!==null)window.clearInterval(timer);if(window.invokeCSharpAction===invoke)delete window.invokeCSharpAction}}}
