import assert from "node:assert/strict";import test from "node:test";import {h} from "preact";import render from "preact-render-to-string";import {App,fileName} from "../src/components/app";import {lastLtcText} from "../src/components/receive-panel";import {appStore} from "../src/store";import {fakeState} from "../src/testing/fake-host";

test("App keeps the operational panels in the server-rendered shell",()=>{const state=fakeState();appStore.value.host.state=state;appStore.value.host.clock=state.currentClock;const html=render(h(App,{}));for(const text of ["動作モード","LTC受信","内部生成","ジャンプ判定","TC 入出力","Cue-Sync 送信設定","送信ログ","ホスト管理","OSC ポン出し","実行モード","編集モード","フリーラン","発火後オートミュート","NEXT CUE","キューリスト"])assert.ok(html.includes(text),`missing rendered text: ${text}`);const modeControls=html.match(/<div class="mode">([\s\S]*?)<\/div>/)?.[1]??"";assert.doesNotMatch(modeControls,/>停止<\/button>/)});

test("TC panel switches with state.mode",()=>{const state=fakeState();appStore.value.host.state=state;appStore.value.host.clock=state.currentClock;assert.match(render(h(App,{})),/入力デバイス/);state.mode="generate";const html=render(h(App,{}));assert.match(html,/開始 TC/);assert.match(html,/なし（出力しない）/);assert.doesNotMatch(html,/入力デバイス/)});

test("NEXT CUE countdown uses the latest clock",()=>{const state=fakeState();appStore.value.host.state=state;appStore.value.host.clock={...state.currentClock,framesUntilNextCue:47};assert.match(render(h(App,{})),/T− 47f/);state.nextCue=null;assert.match(render(h(App,{})),/T− --f/)});

test("LTC panel asks for a device when none is selected",()=>{const state=fakeState();state.receive.selectedDeviceId=null;state.transport.status="stopped";state.transport.statusText="停止中";state.transport.locked=false;appStore.value.host.state=state;appStore.value.host.clock=state.currentClock;const html=render(h(App,{}));assert.match(html,/入力デバイスを選んでください/);assert.match(html,/<button class="btn" disabled>再接続<\/button>/)});

test("signal loss shows seconds since the last real LTC frame",()=>{const now=Date.parse("2026-09-14T01:00:10.900Z");assert.equal(lastLtcText("signalLost","2026-09-14T01:00:03.100Z",now),"最終受信 7 秒前");assert.equal(lastLtcText("freerun",null,now),"最終受信なし");assert.equal(lastLtcText("receiving","2026-09-14T01:00:03.100Z",now),null)});

test("auto-muted cue shows MUTE and the unmute countdown in its row and on the MUTE button",()=>{const state=fakeState();state.transport.triggerMuted=true;state.transport.autoMutedCueId="cue-1";state.cues[0]!.runtime.muteCountdownText="0:02";appStore.value.host.state=state;appStore.value.host.clock=state.currentClock;const html=render(h(App,{}));assert.match(html,/<b class="mute-tag">MUTE 0:02<\/b>/);assert.match(html,/自動解除まで 0:02/);state.transport.autoMutedCueId=null;assert.doesNotMatch(render(h(App,{})),/mute-tag/)});

test("footer omits the detail separator when there is no detail text",()=>{const state=fakeState();state.transport.detailText="";state.transport.locked=false;appStore.value.host.state=state;appStore.value.host.clock=state.currentClock;const html=render(h(App,{}));assert.match(html,/LTC INPUT UNLOCK<\/span>/);state.transport.detailText="CH 1";assert.match(render(h(App,{})),/LTC INPUT UNLOCK · CH 1<\/span>/)});

test("cue rows are keyboard focusable and labelled",()=>{const state=fakeState();appStore.value.host.state=state;appStore.value.host.clock=state.currentClock;const html=render(h(App,{}));assert.match(html,/class="row[^"]*"[^>]*tabindex="0"[^>]*aria-label="本編 IN 01:23:40:00"/)});

test("monitor shows the wave peak level in dBFS, or -- without a wave",()=>{const state=fakeState();appStore.value.host.state=state;appStore.value.host.clock=state.currentClock;appStore.value.host.wave=null;assert.match(render(h(App,{})),/UNLOCK \/ -- dBFS|LOCK \/ -- dBFS/);appStore.value.host.wave={sampleRate:48000,windowMs:3.3,min:[],max:[],levelDbfs:-12.34};assert.match(render(h(App,{})),/LOCK \/ −12.3 dBFS/);appStore.value.host.wave=null});

test("recent projects are listed in the project menu by file name",()=>{assert.equal(fileName("/Users/a/show/opening.json"),"opening.json");assert.equal(fileName("C:\\shows\\night.json"),"night.json");const state=fakeState();state.project.recentFiles=["/tmp/a/first.json","/tmp/b/second.json"];state.transport.signalErrorRatePercent=0.4;appStore.value.host.state=state;appStore.value.host.clock=state.currentClock;const html=render(h(App,{}));assert.match(html,/誤り率 0.4%/);assert.doesNotMatch(html,/first.json/)});
