import type {JSX,ComponentChildren} from "preact";
import {useEffect,useState} from "preact/hooks";
import type {CueDto,FrameRate,HostDto,ProtocolError} from "../protocol";
import {buildCueDraft,cueToForm,emptyCueForm,fieldErrorsFor,type CueForm} from "../cue-draft";
import {command} from "../commands";
import {TimecodeInput,frameMaximum} from "./timecode-input";

export function ModalShell(p:{title:string;close:()=>void;children:ComponentChildren;wide?:boolean;class?:string;titleExtra?:ComponentChildren}) {useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!e.isComposing){e.preventDefault();p.close()}};window.addEventListener("keydown",key,true);return()=>window.removeEventListener("keydown",key,true)},[p.close]);return <div class="modal-shade" onMouseDown={e=>{if(e.target===e.currentTarget)p.close()}}><div class={`dialog ${p.wide?"wide":""} ${p.class??""}`} role="dialog" aria-modal="true" onKeyDown={(e:JSX.TargetedKeyboardEvent<HTMLDivElement>)=>e.stopPropagation()}><div class="dialog-title"><b>{p.title}</b>{p.titleExtra}<button class="btn" onClick={p.close}>閉じる</button></div>{p.children}</div></div>}
const Shell=ModalShell;
const Err=({errors,name}:{errors:Record<string,string>;name:string})=><small class="field-error">{errors[name]??""}</small>;
const Field=({label,name,errors,children}:{label:string;name:string;errors:Record<string,string>;children:ComponentChildren})=><label class="form-field"><span>{label}</span>{children}<Err errors={errors} name={name}/></label>;
const rates:FrameRate[]=["24","25","29.97df","30"];
const Row=({label,name,errors,title,top,children}:{label:string;name?:string;errors:Record<string,string>;title?:string;top?:boolean;children:ComponentChildren})=><div class={`cue-row ${top?"top":""}`}><span class="lbl" title={title}>{label}</span><div class="ctl">{children}{name&&errors[name]&&<small class="field-error">{errors[name]}</small>}</div></div>;

export function CueDialog({cue,frameRate,hosts,close,done}:{cue?:CueDto;frameRate:CueForm["frameRate"];hosts:HostDto[];close:()=>void;done:()=>void}) {
 const[f,setF]=useState<CueForm>(()=>cue?cueToForm(cue):{...emptyCueForm(frameRate),targetHostIds:hosts.map(h=>h.id)});const[errors,setErrors]=useState<Record<string,string>>({});const set=<K extends keyof CueForm>(k:K,v:CueForm[K])=>setF(x=>({...x,[k]:v}));
 const tc=(key:"triggerTime"|"sendTimecode"|"triggerOffset"|"autoUnmuteAfter",label:string,{signed=false,disabled=false}={})=><TimecodeInput ariaLabel={label} value={f[key]} frameRate={f.frameRate} signed={signed} disabled={disabled} required={key==="triggerTime"} onChange={v=>set(key,v)}/>;
 const check=(key:"enabled"|"sendTriggerTimeAsSeconds"|"autoMuteOnFire",label:string)=><label class="check"><input type="checkbox" checked={f[key]} onChange={e=>set(key,e.currentTarget.checked)}/>{label}</label>;
 const optionalTc=(key:"sendTimecode"|"autoUnmuteAfter",label:string,enabled:boolean,initial:string)=><div class="check-row"><label class="check"><input type="checkbox" aria-label={`${label}を指定`} disabled={!enabled} checked={f[key]!==""} onChange={e=>set(key,e.currentTarget.checked?initial:"")}/>指定</label>{tc(key,label,{disabled:!enabled||f[key]===""})}</div>;
 const save=async(e:Event)=>{e.preventDefault();const result=buildCueDraft(f);if(!result.draft){setErrors(result.errors);return}try{await command(cue?"cue.update":"cue.add",cue?{id:cue.id,cue:result.draft}:{cue:result.draft});done()}catch(error){setErrors(fieldErrorsFor(error as ProtocolError,"cue"))}};
 const rate=<label class="cue-frame-rate"><span>基準フレームレート</span><select class="field" value={f.frameRate} onChange={e=>set("frameRate",e.currentTarget.value as FrameRate)}>{rates.map(x=><option value={x}>{x} fps</option>)}</select><small>FF 00–{String(frameMaximum(f.frameRate)).padStart(2,"0")}</small></label>;
 return <Shell title={cue?"キューを編集":"キューを追加"} close={close} class="cue" titleExtra={rate}><form onSubmit={save} class="cue-edit">
  <Row label="名前" name="name" errors={errors}><input autofocus class="field" aria-label="名前" value={f.name} onInput={e=>set("name",e.currentTarget.value)}/></Row>
  <Row label="トリガー時間" name="triggerTime" errors={errors}>{tc("triggerTime","トリガー時間")}</Row>
  <Row label="トリガーオフセット" name="triggerOffset" errors={errors} title="発火タイミングを±ずらします。実際の発火時刻 = トリガー時間 ± この値">{tc("triggerOffset","トリガーオフセット",{signed:true})}</Row>
  <Row label="OSCアドレス" name="oscAddress" errors={errors} top><input class="field mono" aria-label="OSCアドレス" value={f.oscAddress} onInput={e=>set("oscAddress",e.currentTarget.value)}/><span class="hint">追加アドレス（1行1件・引数なしで一緒に送信されます）</span><textarea class="mono" aria-label="追加アドレス" value={f.additionalOscAddresses} onInput={e=>set("additionalOscAddresses",e.currentTarget.value)}/>{errors.additionalOscAddresses&&<small class="field-error">{errors.additionalOscAddresses}</small>}</Row>
  <Row label="TC秒数送信" errors={errors}>{check("sendTriggerTimeAsSeconds","タイムコードを秒数(float)で先頭引数に追加")}</Row>
  <Row label="送信タイムコード" name="sendTimecode" errors={errors} title="秒数送信で送るタイムコード。未指定ならトリガー時間をそのまま送ります">{optionalTc("sendTimecode","送信タイムコード",f.sendTriggerTimeAsSeconds,f.triggerTime||"00:00:00:00")}</Row>
  <Row label="発火時ミュート" errors={errors} title="このキューの発火と同時にMUTE（自動キュー発火の停止）を掛けます。再生中に不慮のTCが飛んできても他のキューが誤発火しません">{check("autoMuteOnFire","発火と同時に自動でミュートする")}</Row>
  <Row label="ミュート解除" name="autoUnmuteAfter" errors={errors} title="指定時間の経過後にMUTEを自動解除します。未指定なら手動で解除するまでミュートを維持します">{optionalTc("autoUnmuteAfter","ミュート解除時間",f.autoMuteOnFire,"00:00:00:00")}</Row>
  <Row label="OSC引数" name="arguments" errors={errors} top title="type:value を 1 行 1 件。例: int32:1 / float32:0.5 / string:GO"><textarea class="mono" aria-label="OSC引数" placeholder={'int32:1\nfloat32:0.5\nstring:GO'} value={f.argumentsText} onInput={e=>set("argumentsText",e.currentTarget.value)}/></Row>
  <Row label="送信先ホスト" name="targetHostIds" errors={errors} top><div class="host-pick"><div class="host-pick-actions"><button type="button" class="btn mini" disabled={!hosts.length} onClick={()=>set("targetHostIds",hosts.map(h=>h.id))}>全選択</button><button type="button" class="btn mini" disabled={!f.targetHostIds.length} onClick={()=>set("targetHostIds",[])}>全解除</button></div><div class="host-pick-list">{hosts.length?hosts.map(h=><label class="check"><input type="checkbox" checked={f.targetHostIds.includes(h.id)} onChange={e=>set("targetHostIds",e.currentTarget.checked?[...f.targetHostIds,h.id]:f.targetHostIds.filter(x=>x!==h.id))}/>{h.name}</label>):<span class="host-pick-empty">ホストが未登録です。<br/>先に「ホスト管理」からホストを追加してください</span>}</div></div></Row>
  <Row label="メモ" name="memo" errors={errors} top><textarea aria-label="メモ" value={f.memo} onInput={e=>set("memo",e.currentTarget.value)}/></Row>
  <Row label="" errors={errors}>{check("enabled","有効")}</Row>
  <div class="dialog-actions"><button type="button" class="btn" onClick={close}>キャンセル</button><button class="btn primary">{cue?"更新":"追加"}</button></div>
 </form></Shell>
}

export function DuplicateDialog({cue,close,done}:{cue:CueDto;close:()=>void;done:()=>void}) {const[count,setCount]=useState(2),[interval,setInterval]=useState("00:00:00:00"),[error,setError]=useState("");
return <Shell title="連続複製" close={close}><form class="simple-form" onSubmit={async e=>{e.preventDefault();try{await command("cue.duplicate",{id:cue.id,count,interval});done()}catch(err){setError((err as ProtocolError).message)}}}>
<label>複製数<input class="field count" type="number" min="1" max="500" value={count} onInput={e=>setCount(Number(e.currentTarget.value))}/></label>
<div class="simple-row"><span>間隔</span><TimecodeInput ariaLabel="複製の間隔" value={interval} frameRate={cue.frameRate} onChange={setInterval}/></div>
<small class="hint">「{cue.name}」の {cue.effectiveTriggerTime} から間隔ずつ後ろに並べます</small>
{error&&<small class="field-error">{error}</small>}
<div class="dialog-actions"><button type="button" class="btn" onClick={close}>キャンセル</button><button class="btn primary">複製</button></div>
</form></Shell>}

export function BatchDialog({ids,hosts,frameRate,close,done,notice}:{ids:string[];hosts:HostDto[];frameRate:FrameRate;close:()=>void;done:()=>void;notice:(s:string)=>void}) {const[active,setActive]=useState(new Set<string>()),[values,setValues]=useState<Record<string,unknown>>({});const[errors,setErrors]=useState<Record<string,string>>({});const fields:Record<string,string>={oscAddress:"OSCアドレス",additionalOscAddresses:"追加アドレス（カンマ区切り）",sendTriggerTimeAsSeconds:"TC秒数送信",sendTimecode:"送信タイムコード",targetHostIds:"送信先ホスト",triggerOffset:"トリガーオフセット",autoMuteOnFire:"発火時ミュート",autoUnmuteAfter:"ミュート解除",memo:"メモ",enabled:"有効"};const timecodeKeys=["sendTimecode","triggerOffset","autoUnmuteAfter"];return <Shell title={`${ids.length} 件を一括編集`} close={close} wide><form class="batch-form" onSubmit={async e=>{e.preventDefault();const changes:Record<string,unknown>={};for(const k of active){let v=values[k];if(k==="additionalOscAddresses")v=String(v??"").split(",").map(x=>x.trim()).filter(Boolean);if(timecodeKeys.includes(k)&&v==="")v=null;changes[k]=v}try{const r=await command("cue.batchUpdate",{ids,changes}) as {offsetSkipped:number};if(r.offsetSkipped>0)notice(`${r.offsetSkipped} 件はオフセット適用後の時刻が範囲外のためオフセットを付けませんでした`);done()}catch(error){setErrors(fieldErrorsFor(error as ProtocolError,"changes"))}}}>{Object.entries(fields).map(([k,label])=><div class="batch-row"><label><input type="checkbox" checked={active.has(k)} onChange={e=>{const n=new Set(active);e.currentTarget.checked?n.add(k):n.delete(k);setActive(n)}}/>{label}</label><div>{["enabled","sendTriggerTimeAsSeconds","autoMuteOnFire"].includes(k)?<input type="checkbox" onChange={e=>setValues({...values,[k]:e.currentTarget.checked})}/>:k==="targetHostIds"?<div>{hosts.map(h=><label><input type="checkbox" onChange={e=>{const a=(values[k] as string[]|undefined)??[];setValues({...values,[k]:e.currentTarget.checked?[...a,h.id]:a.filter(x=>x!==h.id)})}}/>{h.name}</label>)}</div>:timecodeKeys.includes(k)?<TimecodeInput ariaLabel={label} value={String(values[k]??"")} frameRate={frameRate} signed={k==="triggerOffset"} onChange={v=>setValues({...values,[k]:v})}/>:<input class="field" value={String(values[k]??"")} onInput={e=>setValues({...values,[k]:e.currentTarget.value})}/>}<Err errors={errors} name={k}/></div></div>)}<div class="dialog-actions"><button type="button" class="btn" onClick={close}>キャンセル</button><button class="btn primary" disabled={!active.size}>適用</button></div></form></Shell>}
export function ConfirmDialog({message,close,confirm}:{message:string;close:()=>void;confirm:()=>void}) {return <Shell title="確認" close={close}><div class="confirm-body">{message}</div><div class="dialog-actions"><button class="btn" onClick={close}>キャンセル</button><button class="btn danger" onClick={confirm}>削除</button></div></Shell>}
