<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseWPF Condition="'$(TargetFramework)' == 'net8.0-windows'">true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="Xunit.StaFact" Version="1.1.11" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TimecodeBridge\TimecodeBridge.csproj" Condition="'$(TargetFramework)' == 'net8.0-windows'" />
    <ProjectReference Include="..\..\src\TimecodeBridge.Core\TimecodeBridge.Core.csproj" />
    <ProjectReference Include="..\..\src\TimecodeBridge.macOS\TimecodeBridge.macOS.csproj" />
  </ItemGroup>

</Project>
